export const propiedades = [
  {
    id: 1,
    operacion: "Venta",
    estado: "Venta",
    tipoDePropiedad: "Departamento",
    ubicacion: "La Plata Centro",
    titulo: "Departamento moderno",
    precio: 120000,
    metrosCuadrados: 80,
    ambientes: 4,
    dormitorios: 2,
    cocheras: 1,
    baños: 1,
    antiguedad: 5,
    expensas: 15000,
    videos: [
      "/video.mp4"
    ] ,
    imgs: [
      "https://picsum.photos/400/300?1",
      "https://picsum.photos/400/300?2",
      "https://picsum.photos/400/300?3",
      "https://picsum.photos/400/300?4",
    ],
    descripcion: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ab, aliquid? Sequi tempora beatae vitae? Est porro nisi molestiae exercitationem accusamus animi, adipisci, aliquam quos sed neque qui. Accusamus, nam nisi. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident quod sed nulla assumenda porro atque doloribus consectetur, consequatur in minus quasi iste tempora eos impedit vel possimus alias commodi nesciunt!",
    vendedor: "alguien",
  },
  {
    id: 2,
    operacion: "Venta",
    estado: "Alquiler",
    tipoDePropiedad: "Casa",
    ubicacion: "City Bell",
    titulo: "Casa familiar amplia",
    precio: 185000,
    metrosCuadrados: 220,
    ambientes: 6,
    dormitorios: 4,
    cocheras: 2,
    baños: 3,
    antiguedad: 12,
    expensas: 0,
    imgs: [
      "https://picsum.photos/400/300?3",
      "https://picsum.photos/400/300?4",
    ],
  },
  {
    id: 3,
    operacion: "Alquiler",
    estado: "reservado",
    tipoDePropiedad: "Departamento",
    ubicacion: "La Plata Centro",
    titulo: "Depto luminoso céntrico",
    precio: 95000,
    metrosCuadrados: 55,
    ambientes: 3,
    dormitorios: 1,
    cocheras: 0,
    baños: 1,
    antiguedad: 8,
    expensas: 12000,
    imgs: [
      "https://picsum.photos/400/300?5",
      "https://picsum.photos/400/300?6",
    ],
  },
  {
    id: 4,
    operacion: "Venta",
    estado: "Venta",
    tipoDePropiedad: "PH",
    ubicacion: "Tolosa",
    titulo: "PH reciclado con patio",
    precio: 140000,
    metrosCuadrados: 110,
    ambientes: 4,
    dormitorios: 2,
    cocheras: 1,
    baños: 2,
    antiguedad: 20,
    expensas: 0,
    imgs: [
      "https://picsum.photos/400/300?7",
      "https://picsum.photos/400/300?8",
    ],
  },
  {
    id: 5,
    operacion: "Alquiler",
    estado: "Alquiler",
    tipoDePropiedad: "Departamento",
    ubicacion: "Gonnet",
    titulo: "Monoambiente moderno",
    precio: 70000,
    metrosCuadrados: 35,
    ambientes: 1,
    dormitorios: 0,
    cocheras: 0,
    baños: 1,
    antiguedad: 2,
    expensas: 8000,
    imgs: [
      "https://picsum.photos/400/300?9",
      "https://picsum.photos/400/300?10",
    ],
  },
  {
    id: 6,
    operacion: "Venta",
    estado: "reservado",
    tipoDePropiedad: "Casa",
    ubicacion: "Villa Elisa",
    titulo: "Casa con jardín grande",
    precio: 210000,
    metrosCuadrados: 300,
    ambientes: 7,
    dormitorios: 5,
    cocheras: 2,
    baños: 3,
    antiguedad: 15,
    expensas: 0,
    imgs: [
      "https://picsum.photos/400/300?11",
      "https://picsum.photos/400/300?12",
    ],
  },
  {
    id: 7,
    operacion: "Alquiler",
    estado: "Venta",
    tipoDePropiedad: "Departamento",
    ubicacion: "Ringuelet",
    titulo: "Depto cómodo y funcional",
    precio: 88000,
    metrosCuadrados: 60,
    ambientes: 3,
    dormitorios: 2,
    cocheras: 0,
    baños: 1,
    antiguedad: 10,
    expensas: 10000,
    imgs: [
      "https://picsum.photos/400/300?13",
      "https://picsum.photos/400/300?14",
    ],
  },
  {
    id: 8,
    operacion: "Venta",
    estado: "Alquiler",
    tipoDePropiedad: "Casa",
    ubicacion: "Ensenada",
    titulo: "Casa con pileta",
    precio: 240000,
    metrosCuadrados: 280,
    ambientes: 6,
    dormitorios: 4,
    cocheras: 2,
    baños: 3,
    antiguedad: 18,
    expensas: 0,
    imgs: [
      "https://picsum.photos/400/300?15",
      "https://picsum.photos/400/300?16",
    ],
  },
  {
    id: 9,
    operacion: "Alquiler",
    estado: "reservado",
    tipoDePropiedad: "PH",
    ubicacion: "Los Hornos",
    titulo: "PH económico",
    precio: 65000,
    metrosCuadrados: 70,
    ambientes: 3,
    dormitorios: 2,
    cocheras: 0,
    baños: 1,
    antiguedad: 25,
    expensas: 5000,
    imgs: [
      "https://picsum.photos/400/300?17",
      "https://picsum.photos/400/300?18",
    ],
  },
  {
    id: 10,
    operacion: "Venta",
    estado: "Venta",
    tipoDePropiedad: "Departamento",
    ubicacion: "La Plata Centro",
    titulo: "Depto premium",
    precio: 170000,
    metrosCuadrados: 95,
    ambientes: 4,
    dormitorios: 2,
    cocheras: 1,
    baños: 2,
    antiguedad: 3,
    expensas: 20000,
    imgs: [
      "https://picsum.photos/400/300?19",
      "https://picsum.photos/400/300?20",
    ],
  },
  {
    id: 11,
    operacion: "Alquiler",
    estado: "Alquiler",
    tipoDePropiedad: "Departamento",
    ubicacion: "Gonnet",
    titulo: "Depto luminoso",
    precio: 90000,
    metrosCuadrados: 65,
    ambientes: 3,
    dormitorios: 2,
    cocheras: 1,
    baños: 1,
    antiguedad: 6,
    expensas: 11000,
    imgs: ["https://picsum.photos/400/300?21"],
  },
  {
    id: 12,
    operacion: "Venta",
    estado: "reservado",
    tipoDePropiedad: "Casa",
    ubicacion: "City Bell",
    titulo: "Casa moderna minimalista",
    precio: 260000,
    metrosCuadrados: 250,
    ambientes: 5,
    dormitorios: 3,
    cocheras: 2,
    baños: 2,
    antiguedad: 4,
    expensas: 0,
    imgs: ["https://picsum.photos/400/300?22"],
  },
  {
    id: 13,
    operacion: "Alquiler",
    estado: "dado de baja",
    tipoDePropiedad: "PH",
    ubicacion: "Tolosa",
    titulo: "PH accesible",
    precio: 60000,
    metrosCuadrados: 60,
    ambientes: 2,
    dormitorios: 1,
    cocheras: 0,
    baños: 1,
    antiguedad: 30,
    expensas: 4000,
    imgs: ["https://picsum.photos/400/300?23"],
  },
  {
    id: 14,
    operacion: "Venta",
    estado: "Alquiler",
    tipoDePropiedad: "Departamento",
    ubicacion: "La Plata Centro",
    titulo: "Depto con balcón",
    precio: 150000,
    metrosCuadrados: 85,
    ambientes: 4,
    dormitorios: 2,
    cocheras: 1,
    baños: 2,
    antiguedad: 7,
    expensas: 14000,
    imgs: ["https://picsum.photos/400/300?24"],
  },
  {
    id: 15,
    operacion: "Alquiler",
    estado: "reservado",
    tipoDePropiedad: "Casa",
    ubicacion: "Villa Elisa",
    titulo: "Casa tranquila",
    precio: 110000,
    metrosCuadrados: 180,
    ambientes: 5,
    dormitorios: 3,
    cocheras: 1,
    baños: 2,
    antiguedad: 14,
    expensas: 0,
    imgs: ["https://picsum.photos/400/300?25"],
  },
  {
    id: 16,
    operacion: "Venta",
    estado: "Venta",
    tipoDePropiedad: "Casa",
    ubicacion: "Ensenada",
    titulo: "Casa amplia familiar",
    precio: 195000,
    metrosCuadrados: 230,
    ambientes: 6,
    dormitorios: 4,
    cocheras: 2,
    baños: 3,
    antiguedad: 10,
    expensas: 0,
    imgs: ["https://picsum.photos/400/300?26"],
  },
  {
    id: 17,
    operacion: "Alquiler",
    estado: "Alquiler",
    tipoDePropiedad: "Departamento",
    ubicacion: "Ringuelet",
    titulo: "Depto práctico",
    precio: 80000,
    metrosCuadrados: 50,
    ambientes: 2,
    dormitorios: 1,
    cocheras: 0,
    baños: 1,
    antiguedad: 9,
    expensas: 9000,
    imgs: ["https://picsum.photos/400/300?27"],
  },
  {
    id: 18,
    operacion: "Venta",
    estado: "reservado",
    tipoDePropiedad: "PH",
    ubicacion: "Los Hornos",
    titulo: "PH amplio con patio",
    precio: 135000,
    metrosCuadrados: 120,
    ambientes: 4,
    dormitorios: 2,
    cocheras: 1,
    baños: 2,
    antiguedad: 22,
    expensas: 0,
    imgs: ["https://picsum.photos/400/300?28"],
  },
  {
    id: 19,
    operacion: "Alquiler",
    estado: "Venta",
    tipoDePropiedad: "Departamento",
    ubicacion: "Gonnet",
    titulo: "Depto moderno chico",
    precio: 75000,
    metrosCuadrados: 40,
    ambientes: 1,
    dormitorios: 0,
    cocheras: 0,
    baños: 1,
    antiguedad: 1,
    expensas: 7000,
    imgs: ["https://picsum.photos/400/300?29"],
  },
  {
    id: 20,
    operacion: "Venta",
    estado: "Alquiler",
    tipoDePropiedad: "Casa",
    ubicacion: "City Bell",
    titulo: "Casa con parque",
    precio: 275000,
    metrosCuadrados: 320,
    ambientes: 7,
    dormitorios: 5,
    cocheras: 2,
    baños: 4,
    antiguedad: 8,
    expensas: 0,
    imgs: ["https://picsum.photos/400/300?30"],
  },
  {
    id: 21,
    operacion: "Alquiler",
    estado: "reservado",
    tipoDePropiedad: "PH",
    ubicacion: "Tolosa",
    titulo: "PH cómodo",
    precio: 68000,
    metrosCuadrados: 65,
    ambientes: 3,
    dormitorios: 2,
    cocheras: 0,
    baños: 1,
    antiguedad: 18,
    expensas: 6000,
    imgs: ["https://picsum.photos/400/300?31"],
  },
  {
    id: 22,
    operacion: "Venta",
    estado: "Venta",
    tipoDePropiedad: "Departamento",
    ubicacion: "La Plata Centro",
    titulo: "Depto invertible",
    precio: 160000,
    metrosCuadrados: 78,
    ambientes: 3,
    dormitorios: 2,
    cocheras: 1,
    baños: 2,
    antiguedad: 6,
    expensas: 13000,
    imgs: ["https://picsum.photos/400/300?32"],
  },
  {
    id: 23,
    operacion: "Alquiler",
    estado: "Alquiler",
    tipoDePropiedad: "Departamento",
    ubicacion: "Los Hornos",
    titulo: "Depto básico",
    precio: 72000,
    metrosCuadrados: 45,
    ambientes: 2,
    dormitorios: 1,
    cocheras: 0,
    baños: 1,
    antiguedad: 12,
    expensas: 8000,
    imgs: ["https://picsum.photos/400/300?33"],
  },
  {
    id: 24,
    operacion: "Venta",
    estado: "reservado",
    tipoDePropiedad: "Casa",
    ubicacion: "Villa Elisa",
    titulo: "Casa premium",
    precio: 300000,
    metrosCuadrados: 350,
    ambientes: 8,
    dormitorios: 5,
    cocheras: 3,
    baños: 4,
    antiguedad: 5,
    expensas: 0,
    imgs: ["https://picsum.photos/400/300?34"],
  },
  {
    id: 25,
    operacion: "Alquiler",
    estado: "Venta",
    tipoDePropiedad: "Departamento",
    ubicacion: "Gonnet",
    titulo: "Monoambiente económico",
    precio: 65000,
    metrosCuadrados: 30,
    ambientes: 1,
    dormitorios: 0,
    cocheras: 0,
    baños: 1,
    antiguedad: 2,
    expensas: 5000,
    imgs: ["https://picsum.photos/400/300?35"],
  },
];

export default propiedades;